### ISSUE TITLE
Assign a person responsible for pursuing individuals capable of specifying the requirements

### ISSUE THREAD

**Issue by Jeffrey-Vervoort-KNMI** [EURODEO/e-soh-requirements#24]
We want to deliver a product that meets the needs of the stakeholders. To ensure that the deliverables align with expectations, it is essential to have well defined requirements in this repository. Therefore, we must assign a person responsible for pursuing individuals capable of specifying the requirements.

**Comment by lukas-phaf** [comment]
Stuart suggested that he should be this person, especially for external issues/requirements. Assign these issues to Stuart in github.

**Comment by StuartJMatthews** [comment]
Now we've agreed these should be assigned to me :). I'll close this particular ticket.
