### ISSUE TITLE
Define Key Performance Indicator (KPI) topics

### ISSUE THREAD

**Issue by GijsbertKruithof** [EURODEO/e-soh-requirements#7]
We need to have KPI's to able to test the system in the building phase (WP2).

- [ ] Define what topics we need KPIs for

**Comment by GijsbertKruithof** [comment]
--- some preliminary ideas ---
- Availability of API-service  - uptime %
- Meantime to resolve an issue - MTTR
- Mean time between failure - MTBF
- Mean time to failure - MTTF

**Comment by skremdwd** [comment]
I removed the sub topics (which will get added in the later issue) and added some things we spoke about:

KPI's with regard to:

- data consumers
- pubsub
- metadata (quality?)
- data ingest
- software robustness

**Comment by skremdwd** [comment]
See the current brainstorm data here:

https://github.com/EURODEO/e-soh-kpis/blob/main/kpi-brainstorm.md

**Comment by GijsbertKruithof** [comment]
Finalized the KPI's in Helsinki meeting April 26, 2023
